# Generated by Django 6.0.7 on 2026-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesession',
            name='session_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
