# Generated by Django 6.0.7 on 2026-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_tablesession_session_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestorder',
            options={'ordering': ['guest_number']},
        ),
        migrations.AddField(
            model_name='guestorder',
            name='guest_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
