# Generated by Django 6.0.7 on 2026-07-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_guestorder_options_guestorder_guest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
