# Generated by Django 6.0.7 on 2026-07-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_line_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kots', to='orders.guestorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.kitchenorderticket'),
        ),
    ]
