# Generated by Django 6.0.7 on 2026-07-19 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_kitchenorderticket_orderitem_kot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='kitchenorderticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_kots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitchenorderticket',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('printed', 'Printed'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
