# Generated by Django 6.0.7 on 2026-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percentage')], default='amount', max_length=10),
        ),
    ]
