# Generated by Django 6.0.7 on 2026-07-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='subtotal',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
