# Generated by Django 6.0.7 on 2026-08-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_purchaseitem_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('WASTE', 'Waste'), ('RETURN', 'Purchase Return')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('quantity_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='inventory.material')),
            ],
            options={
                'verbose_name': 'Stock Ledger',
                'verbose_name_plural': 'Stock Ledger',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
