# Generated by Django 6.0.7 on 2026-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('out_of_service', 'Out of Service')], default='available', max_length=20),
        ),
    ]
