# Generated by Django 6.0.7 on 2026-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauranttable',
            options={'ordering': ['area', 'table_number']},
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together={('area', 'table_number')},
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='table_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='name',
        ),
    ]
