# Generated by Django 6.0.7 on 2026-07-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_printer', models.CharField(blank=True, max_length=150)),
                ('kitchen_printer', models.CharField(blank=True, max_length=150)),
                ('report_printer', models.CharField(blank=True, max_length=150)),
                ('receipt_printer', models.CharField(blank=True, max_length=150)),
                ('auto_print_kot', models.BooleanField(default=True)),
                ('auto_print_bill', models.BooleanField(default=False)),
                ('bill_copies', models.PositiveIntegerField(default=1)),
                ('kot_copies', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer Setting',
                'verbose_name_plural': 'Printer Settings',
            },
        ),
    ]
